
import Sidebar from "@/components/sidebar/page"
import Topbar from "@/components/topbar/page";
export const metadata = {
  title: 'Admin - Jabalpur Estate',
  description: 'Generated by VS Reality',
}

export default function RootLayout({ children }) {
  return (
 <> 
  <div className={` flex flex-row`}>
      {/* <div className="fixed inset-0 z-50 my-4 mx-4 h-[calc(100vh-25px)] bg-gray-500 min-h-screen"> */}
      <div className="basis-[22%] z-50 ">
     <Sidebar />
          </div>
          
          <div className='bg-[#f8f8f9]  basis-5/6 z-50'>
          <Topbar/>
          <div className=" my-5 px-5 py-4'">
          {children}
          </div>
         
          </div>
        </div>
 </>
  )
}
